USE [E-commerce]
GO

/****** Object:  Table [dbo].[Calander]    Script Date: 12/14/2020 2:48:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Calander](
	[Date_Time] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Calander] PRIMARY KEY CLUSTERED 
(
	[Date_Time] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

